# Generated by Django 4.2.11 on 2026-06-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_viewedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of clinic/hospital', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Clinic or Hospital Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_timings',
            field=models.CharField(blank=True, help_text='Clinic timings (e.g., Mon-Sat 9AM-6PM)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for Google Maps', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for Google Maps', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(blank=True, help_text='Pincode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserDailyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
