# Generated by Django 4.2.11 on 2026-06-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_doctor_address_doctor_city_doctor_clinic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Existing medical conditions', null=True)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, help_text='Medical registration number', max_length=50, null=True)),
                ('consultation_start_time', models.TimeField(default='09:00')),
                ('consultation_end_time', models.TimeField(default='17:00')),
                ('break_start_time', models.TimeField(default='13:00')),
                ('break_end_time', models.TimeField(default='14:00')),
                ('consultation_duration', models.IntegerField(default=15, help_text='Duration per patient in minutes')),
                ('max_patients_per_day', models.IntegerField(default=20)),
                ('is_accepting_new_patients', models.BooleanField(default=True)),
                ('online_consultation_available', models.BooleanField(default=False)),
                ('online_consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
